### ISSUE TITLE
Maxime Deleyn always opens the previous version in Visual Studio.

### ISSUE THREAD

**Issue by dsmit192** [dsmit192/EHealth#13]
When he open the solution in the emulator he gets the previous version without any changes made to it.

**Comment by dsmit192** [comment]
@maxime-dl  Try this: https://forums.xamarin.com/discussion/45327/newest-version-of-code-not-always-deployed-when-debugging-from-xamarin-studio

**Comment by maxime-dl** [comment]
--- Solved --- I have recloned it, removed the app, cleaned and rebuild+deploy and start debug. Now I have always the latest edited version of the app.
